Add the missing functonality to add an attachment or inline image to …
infobip-community/infobip-api-node-sdk pull request #31
Opened 2023-09-08 12:24 UTC by ukmadlz

…the FormData as reported in #30

2023-09-08 13:32 UTC, strosek approved these changes
Looks good to me. Thanks!

2023-09-11 13:33 UTC, pedrosimoessss commented on src/apis/email.ts
> +          Validator.requiredString(
Shouldn't the attachment be a `Buffer` / `Uint8Array`?

2023-09-11 13:33 UTC, pedrosimoessss commented on test/apis/email.test.ts
> +          data: Fs.readFileSync('./test/apis/email.test.ts'),
🤔 very strange that this test is green, considering that the following test fails:
```
  it('throws if input is invalid', () => {
      expect(() => Validator.requiredString(Fs.readFileSync('./test/apis/email.test.ts'))).toThrowError();
  });
```
maybe some weird jest concurrent thing? 😅

2023-09-17 12:08 UTC, juliacodez requested changes
Double-check all text for correct use of articles. Looks good otherwise.

2023-09-17 12:08 UTC, juliacodez commented on test/apis/email.test.ts
> +  it('exposes a send method that accepts an track argument', async () => {
a track agrument

2023-09-17 12:08 UTC, juliacodez commented on test/apis/email.test.ts
> +  it('exposes a send method that accepts an callbackData argument', async () => {
a callbackData

2023-09-17 12:08 UTC, juliacodez commented on test/apis/email.test.ts
> +  it('exposes a send method that accepts an notifyContentType argument', async () => {
a notifyContentType. Check throughout

2023-09-17 14:31 UTC, juliacodez approved these changes
Looks good, thank you!

2023-09-17 14:41 UTC, merged